title: "Zeping Liu"
author: "Zeping Liu"
description: "Keep trying - This is my motto; there's no more info below :)"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "About me"}
  # - {url: "https://zepliu.github.io/assets/pdf/LIU_CV_202509.pdf", title: "CV"}
  - {file: "research.md", title: "Research"}
  # - {file: "blog.md", title: "Blog"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:zepliu@iu.edu"}
  - {title: X, icon: x-twitter, url: "https://x.com/zepliu05"}
  - {title: Google Scholar, icon: google-scholar, url: "https://scholar.google.com/citations?user=hIwv8O4AAAAJ&hl=en&oi=sra"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
